import * as React from 'react';
import './account.css';
import { EditableText } from '../../../components/controls/editable-text/editable-text';

export class Account extends React.Component {

  public render() {
    return (
      <tr>
        <td className='account'>
          <EditableText
            content='123456'
          />
        </td>
        <td>
          <EditableText
            content='щито-нибудь'
          />
        </td>
        <td>
          <EditableText
            content='щито-нибудь'
          />
        </td>
        <td>
          <EditableText
            content='щито-нибудь'
          />
        </td>
        <td>
          <EditableText
            content='щито-нибудь'
          />
        </td>
        <td>
          <EditableText
            content='щито-нибудь'
          />
        </td>
        <td>
          <EditableText
            content='щито-нибудь'
          />
        </td>
        <td>
          <EditableText
            content='щито-нибудь'
          />
        </td>
        <td>
          <EditableText
            content='щито-нибудь'
          />
        </td>
        <td>
          <EditableText
            content='щито-нибудь'
          />
        </td>
        <td>
          <EditableText
            content='щито-нибудь'
          />
        </td>
        <td>
          <EditableText
            content='щито-нибудь'
          />
        </td>
        <td>
          <EditableText
            content='щито-нибудь'
          />
        </td>
        <td>
          <EditableText
            content='щито-нибудь'
          />
        </td>
        <td>
          <EditableText
            content='щито-нибудь'
          />
        </td>
        <td>
          <EditableText
            content='щито-нибудь'
          />
        </td>
        <td>
          <EditableText
            content='щито-нибудь'
          />
        </td>
        <td>
          <EditableText
            content='щито-нибудь'
          />
        </td>
        <td>
          <EditableText
            content='щито-нибудь'
          />
        </td>
        <td>
          <EditableText
            content='щито-нибудь'
          />
        </td>
        <td>
          <EditableText
            content='щито-нибудь'
          />
        </td>
        <td>
          <EditableText
            content='щито-нибудь'
          />
        </td>
        <td>
          <EditableText
            content='щито-нибудь'
          />
        </td>
        <td>
          <EditableText
            content='щито-нибудь'
          />
        </td>
        <td>
          <EditableText
            content='щито-нибудь'
          />
        </td>
        <td>
          <EditableText
            content='щито-нибудь'
          />
        </td>
      </tr>
    )
  }
}
